server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parenting_app_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  jwt:
    access-secret: test-access-secret
    refresh-secret: test-refresh-secret
    access-expires-minutes: 15
    refresh-expires-days: 14
  google:
    client-id: test-google-client-id
